plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: ryanfb/jekyll-theme-palaios
title: Ryan Baumann - ryanfb.xyz
url: https://ryanfb.xyz
author:
  name: Ryan Baumann
  first_name: Ryan
  last_name: Baumann
  email: ryan.baumann@gmail.com
  twitter: ryanfb
twitter:
  username: ryanfb
  card: summary
social:
  links:
   - https://botsin.space/@ryanfb
   - https://keybase.io/ryanfb
   - https://github.com/ryanfb
