plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-seo-tag
remote_theme: ryanfb/jekyll-theme-palaios
title: ryanfb.github.io
url: https://ryanfb.github.io
author:
  name: Ryan Baumann
  first_name: Ryan
  last_name: Baumann
  email: ryan.baumann@gmail.com
  twitter: ryanfb
twitter:
  username: ryanfb
  card: summary
